### ISSUE TITLE
Links missing from Sync intro

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#494]
The overview in https://help.obsidian.md/Obsidian+Sync/Introduction+to+Obsidian+Sync omits 3 links that are in the Sync sidebar section. I've more than once gone to that page and been surprised to not to find documentation about something I thought was documented (it's happened enough times that now I know to check the sidebar).

Possibly some of them are left out intentionally, but "Limitations" and "Share" should definitely be there, and at that point you may as well include "Local and Remote".

(Also, the "If you want to" text in the list seems redundant —the links titles are pretty clear.)

**Comment by marcusolsson** [comment]
Thank you for the feedback!

My intention has been to suggest resources based on the page they're on. For example, "Introduction to Obsidian Sync" is intended to guide new users, rather than to provide a complete index of Sync resources. Though I agree that the missing links are interesting to a new users.

I'm thinking we could divide the linked resources into "next steps" and "you might also be interested in" (or something like it).

The "next steps" section would add some context to each link, where the "you might also ..." section could just be the link name.

WDYT?

**Comment by colintedford** [comment]
Sounds good to me. I'd probably not name the "next steps" section since it's the main content (I realize you may have only named it for sake of this conversation).

**Comment by ericaxu** [comment]
Thanks for raising the issue @colintedford ! @marcusolsson is no longer working on the repo so I'll weigh in.

Since the guide is named "Intro to Sync", I think it's fine that we omit some of the links that are not introductory level. Users can easily search for them or see them in the file explorer on the left.
