### ISSUE TITLE
Add docs for Publish - Custom navigation

### ISSUE THREAD

**Issue by ericaxu** [obsidianmd/obsidian-help#531]

**Comment by sigrunixia** [comment]
In preparation for addressing this issue with a PR, two questions.

1. Any preferences as to where custom navigation to look?
- [ ] A: As its own file in the navigation
- [ ] B: Included in Manage Sites
- [ ] C: Included in Customising your Site

2. In order to expand a little bit more what each setting does (so users can see more what can be done before buying publish), tables, or not tables? 🍡 

<img width="1136" alt="CleanShot 2023-08-30 at 18 56 33@2x" src="https://github.com/obsidianmd/obsidian-help/assets/68425372/e6016df7-4e81-4004-a1f3-c8e0825a0657">

**Comment by ericaxu** [comment]
> In preparation for addressing this issue with a PR, two questions.
> 
> 1. Any preferences as to where custom navigation to look?
> 
> * [ ]  A: As its own file in the navigation
> * [ ]  B: Included in Manage Sites
> * [ ]  C: Included in Customising your Site
> 
> 2. In order to expand a little bit more what each setting does (so users can see more what can be done before buying publish), tables, or not tables? 🍡
> 
> <img alt="CleanShot 2023-08-30 at 18 56 33@2x" width="1136" src="https://user-images.githubusercontent.com/68425372/264498800-e6016df7-4e81-4004-a1f3-c8e0825a0657.png">

1 - C
2 - Tables but in sentence case for consistency

Thanks for the thoughtful Qs!!
