### ISSUE TITLE
Sync Icon on Mobile

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-help#734]
Sync icon is not visible all the time on mobile, so it's easy to miss conflicts, or not be aware that sync got disabled.

**Comment by sigrunixia** [comment]
@colintedford 
We can link better on this to the thread that helps this; and we should probably bump the official FR more so that we can get an official fix.

**Comment by colintedford** [comment]
It feels a little weird to me to link it from Help; a user might wonder, "If they think this design choice is a problem, why don't they change it?". I think the link to the Sync tips thread probably covers it well enough (I guess the indirection makes the question less likely). It's hard for me to judge, tho, since I obviously have an interest in it. 🙂

**Comment by colintedford** [comment]
On the other hand, it would be good for the docs to mention the Sync icon's location. It looks like they do in callouts on the setup pages, but personally that's not where I would look for that info. The callout should probably also appear on the Troubleshooting page, at least. There isn't really a page about Sync's day-to-day operation — maybe there should be?

**Comment by sigrunixia** [comment]
Sync's Day-to-day operation is partly solved by the merge into the new https://help.obsidian.md/Obsidian+Sync/Set+up+Obsidian+Sync updates.

I think the icon will also be covered under Sync UI at this point. It's about time we get something to explain the visualness of Sync.
