### ISSUE TITLE
Lucide font instead of icons

### ISSUE THREAD

**Issue by mdSlash** [obsidianmd/obsidian-help#751]
Hi there! Could we use the Lucide font in the docs instead of icons? The font is available at https://github.com/iconicFonts/if/tree/main/packs/Lucide. I've tried the font inside Obsidian, and the result is as shown in the following image:

![image](https://github.com/obsidianmd/obsidian-help/assets/128622475/ced0de3d-7179-49db-b43f-e7f801f75227)

**Comment by sigrunixia** [comment]
Any particular reason why you suggest using a font for this? Keep in mind that fonts will need to be embedded in the publish.css, and add slowness to the site. Whereas individual SVG's are quite fast.

**Comment by mdSlash** [comment]
> Any particular reason why you suggest using a font for this? Keep in mind that fonts will need to be embedded in the publish.css, and add slowness to the site. Whereas individual SVG's are quite fast.

I thought it would be easier to just insert the icons as glyphs instead of images, because it's like adjusting font color and size without needing extra CSS.

**Comment by sigrunixia** [comment]
The benefit of the SVG images is that we can only include what images we need. Whereas embedding the font, unless you pick it apart or encode your own version of the font, is going to include data that we will not need, which will bloat the publish.css since we have to base64 encode the font. 

As we have both custom icons and lucide icons, the images will stay for now. We can always re-evaluate down the line.
