### ISSUE TITLE
inaccurate description of allowed characters in "tags"

### ISSUE THREAD

**Issue by skztr** [obsidianmd/obsidian-help#816]
https://help.obsidian.md/Editing+and+formatting/Tags#Tag+format  describes tags as having the following constraints:

> You can use any of the following characters in your tags:
> 
> - Alphabetical letters
> - Numbers
> - Underscore (_)
> - Hyphen (-)
> - Forward slash (/) for Nested tags

However, Obsidian tags also seem to support non-alphabetic characters including:

 - Unicode characters from non-english languages
 - Emoji
 - "Symbols" (such as shapes, arrows, etc)

I suspect that the constraint is more likely something such as "any character not in the General or Supplemental Punctuation code planes, also Underscore, Hyphen, or Forward-slash", but I would love for the documentation to have something accurate, perhaps including a reference to a regex or other definition in whatever parser is actually used.

**Comment by skztr** [comment]
Note: the actual regex appears to be:

```
/(^|\s)#[^\u2000-\u206F\u2E00-\u2E7F'!"#$%&()*+,.:;<=>?@^`{|}~\[\]\\\s]*$/g;
```
and
```
/^#[^\u2000-\u206F\u2E00-\u2E7F'!"#$%&()*+,.:;<=>?@^`{|}~\[\]\\\s]+/;
```
(in `app.js`, found via search for: `= /.*?#\[`(regex mode enabled) in the debug console

see also: https://forum.obsidian.md/t/expose-tags-validation-regex-or-function/78167

as this is not stable/exposed (though it can be found in `app.js`

**Comment by sigrunixia** [comment]
At this current time, even though it is available deep in the application, it is not supported for external use by users. Tags are used directly in the HTML tags for styling, and the help docs are geared towards users who may not otherwise have the knowledge of handling the edge cases that can arise if these extra symbols are used extensively.

I do recommend adding a reply and a ❤️ to the forum post you linked. 

In the future, if we expose and stabilize these, they will be updated here, as well as in the dev docs.
